### PR TITLE
Fix/contract call-#218

### LINKED ISSUE #218: BUG: name management (name assignation)
Name `i3` is assigned to 0x01000B5fE61411C466b70631d7fF070187179Bbf address.

cew_bug3

### PR DESCRIPTION
**Pull request by j-chimienti**
fixes #218 

screen shot 2018-08-23 at 10 09 10 am

**issue:**

finding contract abi via name runs into errors if multiple functions w/ same name

**changes:**

updates to ethFuncs, uiFuncs, and contract class to handle multiple functions in abi w/ same name

1. contract class and ethFuncs / uiFuncs accept contract interaction to accept function or name of function
 - see ethFuncs.prepContractData for ex

1. Promisify sending tx or executing contract to make code more maintainable 
    - separate error handling from casual code
   - remove nesting and awkward code patterns
1. reduce rewritten code for user notification
  - sending tx / contract function displays errors to user (successful txs default as well)

**testing**

https://github.com/EthereumCommonwealth/etherwallet/issues/218#issuecomment-415083751

### CODE REVIEW

File: app/scripts/ethFuncs.js [hunk 1]
```diff
@@ -276,82 +276,58 @@ ethFuncs.decodeOutputs = function decodeOutputs(contractFunction, data) {
...
-    @param string funcName
+    @param string  | contract.abi[n] _FUNCTION
     @param Contract contract
     @param Tx {}
-    @returns {error: bool | error, tx: Tx } if cannot estimate gas
+    @returns {error: bool | error, {tx: Tx, _function: contract.abi.function} } if cannot estimate gas
 
  */
 
 ethFuncs.prepContractData = function(
```
Comment (j-chimienti) [inline app/scripts/ethFuncs.js]: call / execute contract function via name or passing in abi obj

File: app/scripts/uiFuncs.js [hunk 2]
```diff
@@ -168,32 +173,47 @@ uiFuncs.trezorUnlock = function() {
 
 
     Generates tx data over defined network
+
+    @returns Promise<>
  */
-uiFuncs.generateTx = function(txData, callback) {
-    txData = uiFuncs.isTxDataValid(txData);
+uiFuncs.generateTx = function(txData) {
+    return new Promise((resolve, reject) => {
```
Comment (j-chimienti) [inline app/scripts/uiFuncs.js]: generate tx returns promise to bubble up errors

File: app/scripts/uiFuncs.js [hunk 3]
```diff
@@ -297,66 +322,102 @@ function mapTransToWeb3Trans(trans) {
...
-uiFuncs.sendTx = function(signedTx, callback) {
+/*
+    send Tx via ajaxReq or web3
+    notify user tx hash
+    return tx hash
+
+    @returns Promise<data: string txHash | error>
+
+ */
+uiFuncs.sendTx = function(signedTx, notify = true) {
```
Comment (j-chimienti) [inline app/scripts/uiFuncs.js]: notify user on error, default to notify on success 

return promise to catch errors

**Comment by j-chimienti** [comment]
fixes #241 

sendcontracttx

### Validation

1. clear rawTx and signedTx if user changes values
1. add tx unit 

1. set gasLimit and value as numbers
1. gasLimit min = 21,000
1. value min = 0

### todo:

1. add tx unit select
1. set max value of tx.gasLimit based on api call

File: app/scripts/directives/arrayInputDrtv.html [hunk 4]
```diff
@@ -3,16 +3,9 @@
...
-                                                      ng-model="input.displayInput"
-                                                      ng-class="Validator.isValidAddress(input.displayInput) ? 'is-valid' : 'is-invalid'"/>
-                        </div>
-                        <div class="col-xs-1">
-                            <div class="addressIdenticon med" title="Address Indenticon"
-                                 blockie-address="{{input.displayInput}}" watch-var="input.displayInput"></div>
-                        </div>
-                    </div>
+
+                    <address-field  var-name="input.displayInput"/>
```
Comment (j-chimienti) [inline app/scripts/directives/arrayInputDrtv.html]: fixes #239 use address field component for lookup service functionality
